### PR TITLE
Add execution time limit option

### PR DESCRIPTION
**Pull request by mottymilshtein**
Would like to have a time limitation option for execution time only without affecting pending tasks.

### CODE REVIEW

**Comment by rogierschouten** [comment]
Hi @mottymilshtein  that looks like a sound PR, with docs , test and all. Loving it, willing to merge it. 

However, is this solution one in the right direction? After all, whenever the execution timer expires, any locking semantics are broken. So after that, the only thing you can do is stop the program.   

This functionality can easily be emulated outside the library, where you simply wrap the function in a function that sets up this timer.  That way, the lock semantic breaking stays outside the library, 

What do you think?

**Comment by mottymilshtein** [comment]
"whenever the execution timer expires, any locking semantics are broken. So after that, the only thing you can do is stop the program."

Could you please explain what you mean by that?

As far as wrapping my code instead of adding this ability to the package: well this is the nature of open source, we can always take a package and wrap it (or write our own from scratch) but it is far nicer to have the capability built in the package so that instead of adding code we can simply pass a parameter.

**Comment by rogierschouten** [comment]
About locking semantics:  the reason for using async-lock is to guarantee exclusivity.  When the timer expires, the function is still running, but you emit the done event anyway. That means that the next function in the queue will start running as well, and now you lost exclusivity.

It is similar with trying to cancel promises. Proper semantics for that are almost impossible to give in a generic way, but have to be tailored to the application.

**Comment by mottymilshtein** [comment]
Yes this is correct, but it is a feature to prevent a function from holding the lock indefinitely and without using occupation timer (which has it's own drawbacks).

I could add a comment in the code and/or documentation to clarify that the execution timeout doesn't actually stop the execution but only releases the lock for the next task in queue to execute.

On a related note the occupation timer has an issue which never calls the next task in queue when it runs out (calls done with false) - causing all other functions to not run and wait until their own occupation timer runs out or be stuck forever in queue if they didn't define occupation timer (i.e. first function called with occupation timer option passed directly to the acquire method and the second called without such an option for the same key then if the first functions timer runs out the second function will be stuck/blocked indefinitely)

**Comment by rogierschouten** [comment]
I still think that a deadlock is valid and should not be resolved by continuing to use the resource but releasing the lock.  But I'll merge it and publish

**Comment by rogierschouten** [comment]
@mottymilshtein   published as 1.4.0;   and I asked the authors of maxOccupationTime to fix the unit test, thanks for reporting

**Pull request merged**
